// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// clear_points
Rcpp::LogicalVector clear_points(Rcpp::NumericVector x, Rcpp::NumericVector cs, Rcpp::List thresholds, int window_len);
RcppExport SEXP clearskies_clear_points(SEXP xSEXP, SEXP csSEXP, SEXP thresholdsSEXP, SEXP window_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cs(csSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< int >::type window_len(window_lenSEXP);
    __result = Rcpp::wrap(clear_points(x, cs, thresholds, window_len));
    return __result;
END_RCPP
}
// rmse
double rmse(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP clearskies_rmse(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(rmse(x, y));
    return __result;
END_RCPP
}
// exrad
Rcpp::NumericVector exrad(Rcpp::NumericVector dayofyear, int times);
RcppExport SEXP clearskies_exrad(SEXP dayofyearSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dayofyear(dayofyearSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    __result = Rcpp::wrap(exrad(dayofyear, times));
    return __result;
END_RCPP
}
// zenith
Rcpp::NumericVector zenith(Rcpp::NumericVector dayofyear, Rcpp::NumericVector year, double tz, double latitude, double longitude, int interval);
RcppExport SEXP clearskies_zenith(SEXP dayofyearSEXP, SEXP yearSEXP, SEXP tzSEXP, SEXP latitudeSEXP, SEXP longitudeSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dayofyear(dayofyearSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< double >::type tz(tzSEXP);
    Rcpp::traits::input_parameter< double >::type latitude(latitudeSEXP);
    Rcpp::traits::input_parameter< double >::type longitude(longitudeSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    __result = Rcpp::wrap(zenith(dayofyear, year, tz, latitude, longitude, interval));
    return __result;
END_RCPP
}
